"""
Django settings for oauth project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
import sys

# Try to import decouple, fallback to os.environ if not available
try:
    from decouple import config
except ImportError:
    def config(key, default=None, cast=None):
        value = os.environ.get(key, default)
        if cast and value is not None:
            return cast(value)
        return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# Strategy:
#   - Use provided SECRET_KEY if set.
#   - If missing and DEBUG=True OR we are running a build command that includes 'collectstatic', generate an ephemeral key
#     so buildpack/container build (which runs collectstatic) does not fail.
#   - Otherwise (runtime, production) raise.
SECRET_KEY = config('SECRET_KEY', default='')
# Deterministic dev fallback (DO NOT use in production). Safer than committing a real secret.
DEV_FALLBACK_SECRET = 'dev-insecure-secret-key-change-me'
SECRET_KEY = 'django-energy-fallback-key'
ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',') if h.strip()] + ['localhost', '127.0.0.1']

# Render.com supplies an external hostname we can auto-allow if present to avoid DisallowedHost errors.
RENDER_HOST = os.environ.get('RENDER_EXTERNAL_HOSTNAME') or os.environ.get('RENDER_EXTERNAL_URL', '').replace('https://', '').replace('http://', '')
if RENDER_HOST:
    host_clean = RENDER_HOST.strip('/ ')
    if host_clean and host_clean not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host_clean)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # disable default static handling to let WhiteNoise manage it
    'oauth2_provider',
    'social_django',
    'tanqio',
    'corsheaders',
    'rest_framework',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Authenticate OAuth2 tokens after the standard auth middleware
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    # Use Microsoft OAuth2 backend supported by installed social-auth-core
    'social_core.backends.microsoft.MicrosoftOAuth2',
    'social_core.backends.azuread.AzureADOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

# OAuth2 Provider Settings
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': config('OAUTH2_PROVIDER_ACCESS_TOKEN_EXPIRE_SECONDS', default=3600, cast=int),
    'REFRESH_TOKEN_EXPIRE_SECONDS': config('OAUTH2_PROVIDER_REFRESH_TOKEN_EXPIRE_SECONDS', default=86400, cast=int),
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600,
    'ACCESS_TOKEN_MODEL': 'oauth2_provider.AccessToken',
    'APPLICATION_MODEL': 'oauth2_provider.Application',
    'REFRESH_TOKEN_MODEL': 'oauth2_provider.RefreshToken',
    'OAUTH2_VALIDATOR_CLASS': 'tanqio.oauth_validators.CustomOAuth2Validator',
}

# Social Auth Settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH2_KEY', default='')  # set in environment (.env / platform vars)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH2_SECRET', default='')  # set in environment
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['openid', 'email', 'profile']

SOCIAL_AUTH_GITHUB_KEY = config('GITHUB_KEY', default='')
SOCIAL_AUTH_GITHUB_SECRET = config('GITHUB_SECRET', default='')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

SOCIAL_AUTH_FACEBOOK_KEY = config('FACEBOOK_KEY', default='your-facebook-app-id')
SOCIAL_AUTH_FACEBOOK_SECRET = config('FACEBOOK_SECRET', default='your-facebook-app-secret')
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

# Microsoft OAuth2 Settings
# SOCIAL_AUTH_MICROSOFT_OAUTH2_KEY = config('MICROSOFT_KEY', default='86f3de5a-688d-44e8-a65e-916133a29c9b')
# SOCIAL_AUTH_MICROSOFT_OAUTH2_SECRET = config('MICROSOFT_SECRET', default='5dca97fa-5bff-410f-aca4-02190f6d13c9')
# Scopes differ by tenant/app registration; adjust as needed
# SOCIAL_AUTH_MICROSOFT_OAUTH2_SCOPE = ['openid', 'email', 'profile']

# Azure AD OAuth Settings (Alternative to Microsoft OAuth2)
SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = config('AZUREAD_KEY', default='your-azure-client-id')
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = config('AZUREAD_SECRET', default='your-azure-client-secret')
SOCIAL_AUTH_AZUREAD_OAUTH2_TENANT_ID = config('AZURE_TENANT_ID', default='common')
SOCIAL_AUTH_AZUREAD_OAUTH2_SCOPE = ['openid', 'email', 'profile']

# Social Auth Pipeline
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# Social Auth Additional Settings
SOCIAL_AUTH_CLEAN_USERNAMES = True
SOCIAL_AUTH_SANITIZE_REDIRECTS = True
SOCIAL_AUTH_LOGIN_ERROR_URL = 'tanqio:login'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Email Settings for Password Reset
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@yourdomain.com')

# Authentication Settings (already defined above)

# Allow login with email or username
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

# OAuth Provider specific logout settings
SOCIAL_AUTH_GOOGLE_OAUTH2_REVOKE_TOKENS_ON_DISCONNECT = True
SOCIAL_AUTH_GITHUB_REVOKE_TOKENS_ON_DISCONNECT = True
SOCIAL_AUTH_MICROSOFT_OAUTH2_REVOKE_TOKENS_ON_DISCONNECT = True

LOGIN_URL = 'tanqio:login'
LOGIN_REDIRECT_URL = 'tanqio:home'
LOGOUT_REDIRECT_URL = 'tanqio:home'

ROOT_URLCONF = 'oauth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'oauth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
if config('POSTGRES_DB', default=''):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER', default='postgres'),
        'PASSWORD': config('POSTGRES_PASSWORD', default='postgres'),
        'HOST': config('POSTGRES_HOST', default='db'),
        'PORT': config('POSTGRES_PORT', default='5432'),
        'CONN_MAX_AGE': config('POSTGRES_CONN_MAX_AGE', default=60, cast=int),
    }
else:
    # Support DATABASE_URL (e.g. for DigitalOcean / Heroku style provisioning)
    db_url = config('DATABASE_URL', default='')
    if db_url:
        try:
            import dj_database_url
            DATABASES['default'] = dj_database_url.parse(db_url, conn_max_age=60, ssl_require=not DEBUG)
        except Exception:
            pass

## Removed duplicate Postgres override block


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'tanqio' / 'images']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise config
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30  # 30 days

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for React frontend
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5174',
    'http://localhost:3000'
]
CORS_ALLOW_CREDENTIALS = True
APPEND_SLASH = False

# Allow CSRF for local dev origins
CSRF_TRUSTED_ORIGINS = [o.strip() for o in config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000').split(',') if o.strip()]

# External token introspection and revocation (optional)
# Configure these if accepting external tokens and revoking them on logout
RESOURCE_SERVER_INTROSPECTION_URL = config('RESOURCE_SERVER_INTROSPECTION_URL', default='')
RESOURCE_SERVER_CLIENT_ID = config('RESOURCE_SERVER_CLIENT_ID', default='')
RESOURCE_SERVER_CLIENT_SECRET = config('RESOURCE_SERVER_CLIENT_SECRET', default='')
# Optional: allowlist issuer client_ids
OAUTH_INTROSPECTION_ALLOWED_CLIENT_IDS = [cid for cid in [config('RESOURCE_SERVER_ALLOWED_CLIENT_ID', default='')] if cid]
# RFC 7009 revocation endpoint; if set, api_logout will attempt remote revocation
RESOURCE_SERVER_REVOCATION_URL = config('RESOURCE_SERVER_REVOCATION_URL', default='')

# Production security hardening (only activate when not DEBUG)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = 'strict-origin'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    # Allow CORS origins from env (optional) in production
    cors_origins_env = config('CORS_ALLOWED_ORIGINS', default='')
    if cors_origins_env:
        CORS_ALLOWED_ORIGINS = [c.strip() for c in cors_origins_env.split(',') if c.strip()]

    # Logging (structured basic config)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'standard': {
                'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
            },
            'json': {
                '()': 'django.utils.log.ServerFormatter',
                'format': '{"time":"%(asctime)s","level":"%(levelname)s","name":"%(name)s","msg":"%(message)s"}'
            }
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'stream': sys.stdout,
                'formatter': 'standard'
            }
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO'
        },
        'loggers': {
            'django.request': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False
            },
            'oauth2_provider': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False
            }
        }
    }

